### ISSUE TITLE
Incompatible with GSD v2.39.0: createAssistantMessageEventStream removed from @mariozechner/pi-ai

### ISSUE THREAD

**Issue by djimenez18** [rchern/pi-claude-cli#9]
### Description

pi-claude-cli v0.1.0 fails to load as a provider when used with GSD v2.39.0. The extension crashes immediately on first LLM call with:

```
(0 , _piAi.createAssistantMessageEventStream) is not a function
```

### Root Cause

pi-claude-cli's `src/provider.ts` (line 18) imports `createAssistantMessageEventStream` as a factory function:

```ts
import { createAssistantMessageEventStream } from "@mariozechner/pi-ai";
```

In GSD v2.39.0, the `@mariozechner/pi-ai` package replaced this factory function with the `AssistantMessageEventStream` class exported directly. The fix is:

```ts
// Before (v0.1.0 — broken with GSD ≥ 2.39.0)
import { createAssistantMessageEventStream } from "@mariozechner/pi-ai";
const stream = createAssistantMessageEventStream();

// After (working with GSD ≥ 2.39.0)
import { AssistantMessageEventStream } from "@mariozechner/pi-ai";
const stream = new AssistantMessageEventStream();
```

The class `AssistantMessageEventStream` IS exported from v2.39.0's pi-ai — only the `createAssistantMessageEventStream` factory wrapper was removed.

### Affected Files

- `src/provider.ts` — import and usage of the factory function
- `tests/provider.test.ts` — mocks `createAssistantMessageEventStream`

### Steps to Reproduce

1. Install GSD v2.39.0: `npm install -g gsd-pi@2.39.0`
2. Install pi-claude-cli v0.1.0: `npm install -g pi-claude-cli`
3. Configure GSD to use `pi-claude-cli` as default provider
4. Run any GSD command that triggers an LLM call
5. Error: `(0 , _piAi.createAssistantMessageEventStream) is not a function`

### Environment

- GSD: v2.39.0
- pi-claude-cli: v0.1.0
- pi-ai peer dep: `^0.52.0` (package.json) — but GSD v2.39.0 ships a newer version that removed the factory
- Node: v24.13.0
- OS: Windows 11

### Additional Context

The GSD-internal `@gsd/pi-ai` alias resolves to the same package. The v2.38.0 → v2.39.0 changelog doesn't mention this breaking change to the pi-ai API surface, making it a silent break for extension authors.
